// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file MeasurementPacket.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "MeasurementPacket.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool MeasurementPacket_serialize_topic(ucdrBuffer* writer, const MeasurementPacket* topic)
{
    (void) ucdr_serialize_uint16_t(writer, topic->p_type);

    (void) ucdr_serialize_string(writer, topic->p_textmessage);

    (void) ucdr_serialize_uint32_t(writer, topic->id);

    (void) ucdr_serialize_int32_t(writer, topic->timestamp);

    return !writer->error;
}

bool MeasurementPacket_deserialize_topic(ucdrBuffer* reader, MeasurementPacket* topic)
{
    (void) ucdr_deserialize_uint16_t(reader, &topic->p_type);

    (void) ucdr_deserialize_string(reader, topic->p_textmessage, 255);

    (void) ucdr_deserialize_uint32_t(reader, &topic->id);

    (void) ucdr_deserialize_int32_t(reader, &topic->timestamp);

    return !reader->error;
}

uint32_t MeasurementPacket_size_of_topic(const MeasurementPacket* topic, uint32_t size)
{
    uint32_t previousSize = size;
    size += ucdr_alignment(size, 2) + 2;

    size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->p_textmessage) + 1;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
