// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementPacket.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MEASUREMENTPACKET_H_
#define _MEASUREMENTPACKET_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MeasurementPacket_SOURCE)
#define MeasurementPacket_DllAPI __declspec( dllexport )
#else
#define MeasurementPacket_DllAPI __declspec( dllimport )
#endif // MeasurementPacket_SOURCE
#else
#define MeasurementPacket_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MeasurementPacket_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure MeasurementPacket defined by the user in the IDL file.
 * @ingroup MEASUREMENTPACKET
 */
class MeasurementPacket
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementPacket();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementPacket();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MeasurementPacket that will be copied.
     */
    eProsima_user_DllExport MeasurementPacket(
            const MeasurementPacket& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MeasurementPacket that will be copied.
     */
    eProsima_user_DllExport MeasurementPacket(
            MeasurementPacket&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MeasurementPacket that will be copied.
     */
    eProsima_user_DllExport MeasurementPacket& operator =(
            const MeasurementPacket& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MeasurementPacket that will be copied.
     */
    eProsima_user_DllExport MeasurementPacket& operator =(
            MeasurementPacket&& x);

    /*!
     * @brief This function sets a value in member p_type
     * @param _p_type New value for member p_type
     */
    eProsima_user_DllExport void p_type(
            uint16_t _p_type);

    /*!
     * @brief This function returns the value of member p_type
     * @return Value of member p_type
     */
    eProsima_user_DllExport uint16_t p_type() const;

    /*!
     * @brief This function returns a reference to member p_type
     * @return Reference to member p_type
     */
    eProsima_user_DllExport uint16_t& p_type();

    /*!
     * @brief This function copies the value in member p_textmessage
     * @param _p_textmessage New value to be copied in member p_textmessage
     */
    eProsima_user_DllExport void p_textmessage(
            const std::string& _p_textmessage);

    /*!
     * @brief This function moves the value in member p_textmessage
     * @param _p_textmessage New value to be moved in member p_textmessage
     */
    eProsima_user_DllExport void p_textmessage(
            std::string&& _p_textmessage);

    /*!
     * @brief This function returns a constant reference to member p_textmessage
     * @return Constant reference to member p_textmessage
     */
    eProsima_user_DllExport const std::string& p_textmessage() const;

    /*!
     * @brief This function returns a reference to member p_textmessage
     * @return Reference to member p_textmessage
     */
    eProsima_user_DllExport std::string& p_textmessage();
    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            uint32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport uint32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport uint32_t& id();

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            int32_t _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport int32_t timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport int32_t& timestamp();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const MeasurementPacket& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint16_t m_p_type;
    std::string m_p_textmessage;
    uint32_t m_id;
    int32_t m_timestamp;
};

#endif // _MEASUREMENTPACKET_H_